swagger: '2.0'
info:
  description: ' Api Documentation'
  version: '1.0.0'
  title: 'Node Js Boiler Plate'

paths:
  /api/user/signup:
    post:
      tags:
        - 'admin'
      summary: 'Signup'
      description: ''
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
      - in: 'body'
        name: 'body'
        description: 'User can signup with email and password'
        required: true
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
      responses:
        '500':
          description: 'Email Already exist'
        '201':
          description: 'Signup Successfully'


  